In [1]:
import numpy as np

In [2]:
my_list = list(range(4))

# Cast list to np array

In [3]:
my_array = np.array(my_list)

In [4]:
my_array

array([0, 1, 2, 3])

# multidimensional array

In [5]:
my_array2d = np.array([list(range(4)),list(range(4))])

In [7]:
my_array2d

array([[0, 1, 2, 3],
       [0, 1, 2, 3]])

## Shape

In [8]:
my_array2d.shape

(2, 4)

## type

In [9]:
my_array2d.dtype

dtype('int64')

## Initialize with default values(0s or 1s)

In [10]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## initialize with range()

In [13]:
np.arange(5,50,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])

# operações

### produto escalar:

In [15]:
np.arange(5,50,2) * np.arange(5,50,2)

array([  25,   49,   81,  121,  169,  225,  289,  361,  441,  529,  625,
        729,  841,  961, 1089, 1225, 1369, 1521, 1681, 1849, 2025, 2209,
       2401])

### sub, sum

In [16]:
my_array2d - my_array2d

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

### divide o escalar por cada elemento do array

In [20]:
1/my_array2d

/tmp/ipykernel_22562/2915895429.py:1: RuntimeWarning: divide by zero encountered in divide
  1/my_array2d


array([[       inf, 1.        , 0.5       , 0.33333333],
       [       inf, 1.        , 0.5       , 0.33333333]])

### exponenciação

In [21]:
my_array2d**3

array([[ 0,  1,  8, 27],
       [ 0,  1,  8, 27]])

In [22]:
my_array2d**(1/2)

array([[0.        , 1.        , 1.41421356, 1.73205081],
       [0.        , 1.        , 1.41421356, 1.73205081]])

# Indexing

array([0, 1, 2])

In [31]:
aux = lambda x:list(range(x))
array2d = np.array([aux(3),aux(3),aux(3)])

In [32]:
array2d

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [33]:
slice_array = array2d[:2,1:]

In [34]:
slice_array+=2

### modificar o slice modifica o original também... é necessario copiar o array pra evitar isso

In [35]:
array2d

array([[0, 3, 4],
       [0, 3, 4],
       [0, 1, 2]])

In [36]:
copy_array2d = array2d.copy()

In [45]:
arr = np.arange(50).reshape((10,5))

In [46]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [47]:
arr.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49]])

# produto vetorial

In [ ]:
np.dot(arr.T,arr)

In [55]:
np.array([[1,2,3]])

array([[1, 2, 3]])

In [56]:
np.array([[1,2,3]]).T

array([[1],
       [2],
       [3]])

In [57]:
np.array([[1,2,3]]).swapaxes(0,1)

array([[1],
       [2],
       [3]])